### ISSUE TITLE
Scrollbars on lists

### ISSUE THREAD

**Issue by britzl** [britzl/gooey#13]

**Comment by Jerakin** [comment]
My dynamic list is huge and I would love for the user to be able to scroll in it faster, my thought was therefore to implement a scrollbar, but can't figure out a good way. I could figure out _where_ I am in the list with the index of the item, but can't figure out how to change the position of the dynamic list. Ideas?

**Comment by britzl** [comment]
Looking into adding a scrollbar component.

**Comment by britzl** [comment]
Added a scrollbar component in Gooey 7.0.0:

https://github.com/britzl/gooey/releases/tag/7.0.0

**Comment by Jerakin** [comment]
Just checking this out now and it works awesomely!

One thing I noticed is that it doesn't care about the handle size. Do you think it could be a good idea to do that?

Of course this would not mesh well with the "point" scroll you have the Dirty Larry scene (also the html version on the community pages is very outdated)
