### ISSUE TITLE
Example for eloquently handling input consumption

### ISSUE THREAD

**Issue by karlmacklin** [britzl/gooey#16]
I'm looking at the examples, kenneyblue to be specific.
`on_input` contains all the theme specific updates for the buttons, checkboxes etc.
Looking at the theme's file's specific fucntions, the M.button returns the gooey.button call.

I'm adopting this style into a theme of my own, where I have a custom type of buttons. When pressing on (`pressed_now == true`) and fully qualified 'clicks' I want to consume the input.
Reason being that I want interaction on my buttons to take priority and not allow my game area to react to that input. Only on 'accidental' interactions, like releasing on top of the button but not having done the initial press - a non fully qualified click so to say.

My initial thought was to - inside the gui_scripts `on_input`-  save a boolean result for all calls to the theme button function. Then check if any of those were true to know whether or not input should be consumed or not.

At this point I'm thinking I might be doing things wrong, it seems a bit unwieldy. Is there a recommended way for handling input consumption with gooey?

**Comment by britzl** [comment]
Good point! Determining input consumption for a group of components is a bit clunky. I've released a new version of Gooey that simplifies this:

1. Components now have a `consumed` field
2. There's now a new gooey.group() function to collect consume data for multiple components:

```
local gooey = require "gooey.gooey"

function on_input(self, action_id, action)
    local group = gooey.group("group1", function()
        gooey.button("button1/bg", action_id, action, on_pressed, function(button) end)
        gooey.button("button2/bg", action_id, action, on_pressed, function(button) end)
        gooey.radio("radio1/bg", "MYGROUP", action_id, action, function(radio) end, update_radio)
        ...
        -- and so on
    end)
    return group.consumed
end
```

**Comment by karlmacklin** [comment]
awesome!
