### ISSUE TITLE
Incorrect is_enabled?

### ISSUE THREAD

**Issue by Insality** [britzl/gooey#18]
https://github.com/britzl/gooey/blob/3ab5b022a58192f401e24fea1944166e34b07da1/gooey/internal/core.lua#L60

for example: if we have such struct as:
Node1 (enabled) => Node2 (disabled) => Button(enabled)

and check is_enabled(Button) we got enabled of Node1 - true

**Comment by britzl** [comment]
Thank you so much for reporting! Released a fix and a new version just now.
