### ISSUE TITLE
Dynamic list image not change

### ISSUE THREAD

**Issue by tharinducds** [britzl/gooey#35]
When i was scrolling the gooey dynamic list, text variables are scrolled successfully but the images not scrolled successfully.

Discussion link in Forum -  [https://forum.defold.com/t/dynamic-list-image-not-change/48883](https://forum.defold.com/t/dynamic-list-image-not-change/48883).

**Comment by britzl** [comment]
Added an example of how this can be done. You need to track loaded images and the node they are assigned and throw away old data. You should also try to reuse data to not load too much.
