### ISSUE TITLE
Bug: text:gmatch instead of text:gfind?

### ISSUE THREAD

**Issue by lutz-harder** [britzl/gooey#37]
Hi Britzl,

it seems, there is a bug in Gooey: 

In master/gooey/internal/input.lua, line 37, you use:

function M.utf8_gfind(text)
	return **text:gfind**("([%z\1-\127\194-\244][\128-\191]*)")
end

That seems to be deprecated and causes an error. 
I assume, it should be replaced by:

function M.utf8_gfind(text)
	return **text:gmatch**("([%z\1-\127\194-\244][\128-\191]*)")
end

Regards,
Lutz

**Comment by britzl** [comment]
Fixed in 7.2.2
