### ISSUE TITLE
Dynamic lists shows odd behaviour when screen have been resized

### ISSUE THREAD

**Issue by Jerakin** [britzl/gooey#39]
The bottom of the scroll list looks like this when not resizing
![Screen Shot 2019-05-15 at 11 36 30](https://user-images.githubusercontent.com/5273682/57766403-97fe1b80-7707-11e9-8c04-2e8eafb0f89d.png)

But if I resize the screen with `defos.set_window_size(0, 0, 570, 1224)` (from 720, 1280) it looks like this instead
![Screen Shot 2019-05-15 at 11 36 05](https://user-images.githubusercontent.com/5273682/57766526-c2e86f80-7707-11e9-81c1-6bd8a2e91a9c.png)

Quite a lot of padding is added and a extra item can be seen. The data is nil (but it get's set even though I check for nil before doing `gui.set_text()`.

The stencil node have Adjustment Mode: Stretch and Y Anchor: Top

**Comment by britzl** [comment]
Can you share the project so that I can try?

**Comment by Jerakin** [comment]
Eh the project is a mess 😐 could be hard to find it there (inviting you anyway).

I think I found the source of the issue and managed to reproduce it: "Adjustment Mode: Stretch" on stencil nodes gives issues. I think it is possible to reproduce it in gooey example.

In the gui file
`\gooey\themes\kenneyblue\components\dynamiclist.gui`

Set both `bg` and `stencil` to Adjust Mode: Stretch.

You only have to make the window narrower for it to pop up.

![capture2](https://user-images.githubusercontent.com/5273682/57988736-ee65b400-7a91-11e9-860c-31c545be52f6.gif)
![capture](https://user-images.githubusercontent.com/5273682/57988737-ee65b400-7a91-11e9-8e94-443fc89c2bca.gif)

**Comment by britzl** [comment]
Hmm, yeah, since that's a dynamic list it has a fixed amount of list items and they are created on startup. We need to find a way to detect that there's a need for more/less list items and recreate them.

**Comment by Jerakin** [comment]
What do you think would be the best way to do this? Adding a window listener?

**Comment by britzl** [comment]
Well, I think maybe Gooey should have a function that the application can call to set/update the current window width/height. And components can somehow read this value and decide on recreating/updating the view.

**Comment by britzl** [comment]
I've played around with a gooey.get/set_window_size() function that the components can use to detect a change and that all works well. The next problem in the case of a list if to calculate the new size of the stencil node so that it's possible to calculate the number of list item nodes to create.

**Comment by Jerakin** [comment]
> The next problem in the case of a list if to calculate the new size of the stencil node so that it's possible to calculate the number of list item nodes to create.

Would be very handy to call this separately for when you use set_size on a list too.

**Comment by britzl** [comment]
I've decided that it becomes too messy to use stretch adjust mode on lists. It complicates things too much when it comes to visible list item calculations, max scroll amount etc.

I have added support for detecting when the stencil size has changed and will recreate the nodes in the list when this happens.
