### ISSUE TITLE
Scrollbars faulty behaviour when screen have been resized

### ISSUE THREAD

**Issue by Jerakin** [britzl/gooey#40]
It jumps when you click on the handle

![capture](https://user-images.githubusercontent.com/5273682/57890979-ffb48380-7839-11e9-835c-5d6934136025.gif)

**Comment by britzl** [comment]
How do I reproduce this? Can you provide an example or instruction on how to modify existing examples and how to test?

**Comment by Jerakin** [comment]
Change the resolution of your game to a super tall one with defos
https://github.com/subsoap/defos/archive/master.zip

I could reproduce it after adding 
`defos.set_window_size(0, 0, 570, 1224)`

in `init` of example/controller.script


Edit: After further testing I think you actually only have to resize the window manually
