### ISSUE TITLE
Text limit for input box

### ISSUE THREAD

**Issue by nicloay** [britzl/gooey#5]
Limit number of characters for input boxes. 

At `function M.input(node_id, keyboard_type, action_id, action)` add additional optional parameter like

`function M.input(node_id, keyboard_type, action_id, action, max_text_width)`

and then in code just check if this parameter is set, don't add new characters to string

**Comment by britzl** [comment]
Good point. I've added a config table as last argument. max_length currently the only supported value. Released gooey 2.0.
