### ISSUE TITLE
No typing input from Android browsers

### ISSUE THREAD

**Issue by DipFlip** [britzl/gooey#66]
I'm not getting any keyboard showing up when clicking the text input fields on the [Gooey demo](https://britzl.github.io/Gooey/). 
If I go to the home screen and back to the browser with the text field already selected, the keyboard will pop up but the text field doesn't respond to any typing. Could it be that some android update has broken something?

Device: Galaxy S10E
OS: Android 11
Browser: Chrome and Firefox
Keyboard: Samsung default and Microsoft Swiftkey

**Comment by britzl** [comment]
There are known problems with text input for Defold in HTML5 on mobile:

https://github.com/defold/defold/issues/3383

**Comment by britzl** [comment]
Refer to linked Defold issue.
