### ISSUE TITLE
Lists are not updated on list refresh since 10.0.0

### ISSUE THREAD

**Issue by paweljarosz** [britzl/gooey#73]
Hello!

So in 9.1.4 everything work as expected, but from 10.0.0 it looks like the dynamic lists are not updating list elements according to refresh function. First observation is that list.pressed_now / over_item_now / over_item are always false, regardless if I really point at the node. Tested on examples provided with Gooey. I see there were some breaking changes in 10.0.0, but can't correlate quickly as of now.

**Comment by britzl** [comment]
Thanks. I will investigate!

**Comment by britzl** [comment]
Found the issue in the examples. `list.over_item` and similar are no longer item indices but rather the items themselves. Check the updated examples to see how it is supposed to work.
